apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App1
  template:
    metadata:
      labels:
      environment: production
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
